### ISSUE TITLE
Use Emacs 27 window-specific faces

### ISSUE THREAD

**Issue by dcolascione** [mina86/auto-dim-other-buffers.el#16]
https://lists.gnu.org/archive/html/emacs-devel/2018-06/msg00224.html is my proposal to add real window-specific face support. You might want to use it to disambiguate multiple windows pointing to the same buffer, as I do in https://github.com/dcolascione/emacs-window-highlight/blob/master/window-highlight.el (which I implemented before I found this mode)

**Comment by mina86** [comment]
I wonder if that actually makes sense. Since I would like to keep backwards compatibility, the code would need various conditional to cope with old and new Emacsen. Given that, it might be better to keep adob in its current form and develop wh to have feature parity with adob.

If you’re interested I can start sending you PRs for wh.
